### ISSUE TITLE
Cross Site Scripting Error with mlab server lookup

### ISSUE THREAD

**Issue by bchase78** [bchase78/ndt-chromeapp#2]
"XMLHttpRequest cannot load http://mlab-ns.appspot.com/ndt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://gfccihbaalajlflddgeahpcakgjifbaa' is therefore not allowed access. The response had HTTP status code 503."

Server must allow Origin with reponse header

CORS

**Comment by pboothe** [comment]
Is this still happening?  We had an mlab-ns outage last week, and so this test might have happened at the same time as the outage.

**Comment by bchase78** [comment]
Its working now. It appears this was the afore mentioned outage.
